require("core.plugin_config.theme")
require("core.plugin_config.lualine")
require("core.plugin_config.todo_comments")
require("core.plugin_config.treesitter")
require("core.plugin_config.rainbow_delimiters")
require("core.plugin_config.telescope")
require("core.plugin_config.nvim_tree")
